In [1]:
import torch  # 引入Pytorch库
print(torch.cuda.is_available())  # 测试GPU是否有效

True


In [ ]:
import torch.nn as nn
import torch
import numpy as np
import matplotlib.pyplot as plt
class LogicNet(nn.Module):  #继承nn.Module类，构建网络模型
    def __init__(self,inputdim,hiddendim,outputdim):  # 初始化函数中确定网络结构
        super(LogicNet,self).__init__()
        self.Linear1 = nn.Linear(inputdim,hiddendim)  # 定义全连接层
        self.Linear2 = nn.Linear(hiddendim,outputdim)  # 定义全连接层
        self.criterion = nn.CrossEntropyLoss()  # 定义交叉熵函数
    
    def forward(self,x):  # 搭建网络模型
        x = self.Linear1(x)  # 将输入数据传入第1搁全连接层
        x = torch.tanh(x)  # 对第1个连接层的结果进行非线性变换（使用tanh函数）
        x = self.Linear2(x)  # 将完成了非线性变换后的数据传入第二个连接层
        return x  # 输出第二个连接层的结果
    
    def predict(self,x):  # 实现LogicNet类的预测接口
        # 调用自身网络模型，并且对结果进行softmax处理，分别得出预测数据中属于每一类的概率
        x = self.forward(x)  # 调用自身网络模型，将结果赋到x中
        pred = torch.softmax(x,dim=1)  # 返回每组预测概率中最大值的索引
    
    def getloss(self,x,y):  # 实现LogicNet类的损失值接口
        y_pred = self.forward(x)
        loss = self.criterion(y_pred,y)  # 计算损失值的交叉熵
        return loss

In [ ]:
model = LogicNet(inputdim=2,hiddendim=3,outputdim=2)  # 实例化模型
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)  # 定义优化器

In [ ]:
x = torch.from_numpy(feature_data).type(torch.FloatTensor)  # 将numpy数据转化为张量  
y = torch.from_numpy(target_data).type(torch.LongTensor)
epochs = 270  # 定义迭代次数
losses = list()  # 定义列表，用于接受每一步的损失值
for i in range(epochs):
    loss = model.getloss(x,y)  # 将数据带入模型进行计算，得到损失值
    losses.append(loss.item())  # 保留这一轮训练的损失值到losses中
    optimizer.zero_grad()  # 清空之前的梯度
    loss.backward()  # 反向传播损失值
    optimizer.step()  # 更新参数

In [4]:
import torch
x = torch.rand(2,1)  # 定义一个张量
print(x.shape)  # 打印张量形状，输出:torch.Size([2,1])
print(x.size())  # 打印张量大小，输出:torch.Size([2, 1])
print(x.reshape([1,2]).shape)  # 先将张量的形状重新塑造，然后打印张量的形状，输出:torch.Size([1, 2])

torch.Size([2, 1])
torch.Size([2, 1])
torch.Size([1, 2])


In [6]:
import torch
torch.manual_seed(2)  # 设置随机数种子  
torch.initial_seed()  # 查看随机数种子，输出:2
torch.randn(2,3)  # 随机生成指定形状的随机值张量
torch.arange(1,10,step=2)  # 在1到10之间，按照步长为2进行取值，输出:tensor([1,3,5,7,9])
torch.linspace(1,9,steps=5)  # 在1到9之间，均匀地取出5个值，输出:tensor([1.,3.,5.,7.,9.])

tensor([[ 0.3923, -0.2236, -0.3195],
        [-1.2050,  1.0445, -0.6332]])

In [8]:
import torch
a = torch.FloatTensor([4])
b = torch.add(a,a)  # 调用torch.add()进行相加
torch.add(a,a,out=b)  # 调用torch.add()进行相加，并且将结果输出给b
a.add_(b)  # 实现 a+=b

tensor([8.])

In [10]:
a = torch.tensor([[1,2],[3,4]])
print(torch.reshape(a,(1,-1)).shape)

torch.Size([1, 4])


In [12]:
b = torch.tensor([[5,6,7],[2,8,0]])
torch.t(b)  # 转置矩阵
torch.transpose(b,dim0=1,dim1=0)  # 转置矩阵
b.permute(1,0)  # 将矩阵的第0维度与第1维度交换
a = torch.tensor([[1,2,3],[4,5,6]])
print(torch.cat([a,b],dim=0))  # 输出:tensor([[1, 2, 3],[4, 5, 6],[5, 6, 7],[2, 8, 0]])
print(torch.cat([a,b],dim=1))  # 输出:tensor([[1, 2, 3, 5, 6, 7],[4, 5, 6, 2, 8, 0]])
torch.chunk(a,chunks=2,dim=0)  # 将张量a沿着第0维度分割成2部分,返回类型是tuple
torch.chunk(a,chunks=2,dim=1)  # 将张量a沿着第1维度分割成2部分,返回类型是tuple

tensor([[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7],
        [2, 8, 0]])
tensor([[1, 2, 3, 5, 6, 7],
        [4, 5, 6, 2, 8, 0]])


(tensor([[1, 2],
         [4, 5]]),
 tensor([[3],
         [6]]))

In [17]:
b = torch.tensor([[5,6,7],[2,8,0]])  # 定义一个二维张量
torch.split(b,split_size_or_sections=(1,2),dim =1)  # 将张量b沿着第1维度分割成两个部分
                                                    # 输出:(tensor([[5],[2]]),tensor([[6, 7],[8, 0]]))
torch.split(b,split_size_or_sections=2,dim =1)  # 将张量b沿着第1维度分割成2部分，每部分按照2个元素进行拆分。不满足指定个数的剩余数据，将会被作为分割数据的最后一部分
torch.gather(b,dim=1,index=torch.tensor([[1,0],[1,2]]))  # 沿着第1维度，按照index的形状进行取值排列。输出tensor([[6, 5],[8, 0]])
torch.index_select(b,dim=0,index=torch.tensor(1))  # 沿着第0维度,取出第一个元素,输出:tensor([[2, 8, 0]])

tensor([[2, 8, 0]])